### ISSUE TITLE
app.ts is repetitive

### ISSUE THREAD

**Issue by dsyme** [githubnext/hello-world#1]
branch: dev

**Comment by colebemis** [comment]
✨✨ Here's [an AI-assisted sketch of how you might approach this issue](https://copilot-workspace-dev.githubnext.com/githubnext/hello-world/issues/1?shareId=e72b8a5a-a746-4e92-bc54-da5cbd16e3e2) saved by @colebemis using Copilot Workspace v0.17

<details open><summary><b>Topic</b></summary>
<br/>

Has the repetitive code in app.ts been refactored or optimized?

</details>

<details open><summary><b>Before</b></summary>
<br/>

* No, the repetitive code in `app.ts` has not been refactored or optimized.
* The file contains repeated lines of code printing the same messages.



</details>
<details open><summary><b>After</b></summary>
<br/>

* Yes, the repetitive code in `app.ts` has been refactored or optimized.
* The file now uses a loop or a function to reduce repetition and improve maintainability.


</details>

<details open><summary><b>Plan</b></summary>
<br/>

undefined

</details>

<details open><summary><b>Sketch of implementation</b></summary>
<br/>

An implementation sketch has not been generated or was not included

<details open><summary><b>Details</b></summary>
<br/>

Code analyzed at 7b69da75bc8b70f4bd1e3f107dea9145019ecd81

</details>
